CREATE TABLE USUARIO(
	Cedula VARCHAR(9) PRIMARY KEY,
	Nombre VARCHAR(10) NOT NULL,
	Apellido1 VARCHAR(10) NOT NULL,
	Apellido2 VARCHAR(10) NOT NULL,
	Codigo VARCHAR(4) NOT NULL,
	TipoUsuarioID INTEGER NOT NULL
);

CREATE TABLE TIPO_USUARIO(
	ID SERIAL PRIMARY KEY,
	Descripcion VARCHAR(20) NOT NULL
);

CREATE TABLE TIPO_ESTADO(
	ID SERIAL PRIMARY KEY,
	Descripcion VARCHAR(20) NOT NULL
);

CREATE TABLE LINEA(
	ID SERIAL PRIMARY KEY,
	EstadoID INTEGER NOT NULL
);

CREATE TABLE LOTE(
	ID VARCHAR(9) PRIMARY KEY,
	Descripcion VARCHAR(20) NOT NULL,
	ProductoID INTEGER NOT NULL,
	CantidadRequerida INTEGER NOT NULL,
	CantidadObtenida INTEGER NOT NULL
);

CREATE TABLE PRODUCTO(
	ID SERIAL PRIMARY KEY,
	Nombre VARCHAR(50) NOT NULL,
	Descripcion VARCHAR(100) NOT NULL
);

CREATE TABLE USUARIO_POR_LINEA(
	Cedula VARCHAR(9) NOT NULL,
	LineaID INTEGER NOT NULL,
	Fecha DATE NOT NULL,
	HoraInicio TIME NOT NULL,
	HoraFinal TIME NOT NULL,
	PRIMARY KEY(Cedula, LineaID)
);

CREATE TABLE TECNICO_POR_LINEA(
	LineaID INTEGER NOT NULL,
	CedulaTecnico VARCHAR(9) NOT NULL,
	Filler INTEGER,
	PRIMARY KEY(LineaID, CedulaTecnico)
);

CREATE TABLE LOTE_POR_LINEA(
	LineaID INTEGER NOT NULL,
	LoteID VARCHAR(9) NOT NULL,
	Fecha DATE NOT NULL,
	HoraInicio TIME NOT NULL,
	HoraFinal TIME NOT NULL,
	PRIMARY KEY(LineaID, LoteID, Fecha, HoraInicio)
);

ALTER TABLE USUARIO
ADD CONSTRAINT keys1
FOREIGN KEY (TipoUsuarioID)
REFERENCES TIPO_USUARIO (ID);

ALTER TABLE USUARIO_POR_LINEA
ADD CONSTRAINT keys2
FOREIGN KEY (Cedula)
REFERENCES USUARIO (Cedula);

ALTER TABLE USUARIO_POR_LINEA
ADD CONSTRAINT keys3
FOREIGN KEY (LineaID)
REFERENCES LINEA (ID);

ALTER TABLE LINEA
ADD CONSTRAINT keys4
FOREIGN KEY (EstadoID)
REFERENCES TIPO_ESTADO (ID);

ALTER TABLE LOTE
ADD CONSTRAINT keys5
FOREIGN KEY (ProductoID)
REFERENCES PRODUCTO (ID);

ALTER TABLE LOTE_POR_LINEA
ADD CONSTRAINT keys6
FOREIGN KEY (LineaID)
REFERENCES LINEA (ID);

ALTER TABLE LOTE_POR_LINEA
ADD CONSTRAINT keys7
FOREIGN KEY (LoteID)
REFERENCES LOTE (ID);

ALTER TABLE TECNICO_POR_LINEA
ADD CONSTRAINT keys8
FOREIGN KEY (LineaID)
REFERENCES LINEA (ID);

ALTER TABLE TECNICO_POR_LINEA
ADD CONSTRAINT keys9
FOREIGN KEY (CedulaTecnico)
REFERENCES USUARIO (Cedula);